# Built-in Variables
author = "YuK"
baseurl = "https://eiskern.com/"
copyright = "YuK"
disqusshortname = ""
googleanalytics = ""
title = "Prologue"
theme = "prologue"

languageCode = "en-us"

[params]
    name = "Jane Doe"
    description = "Hyperspace Engineer"

# intro(top), about, portfolio, contact
[[params.contents]]
    name = "intro"
    title = "Intro"
    href = "top"
    icon = "fa-home"

[[params.contents]]
    name = "about"
    title = "About Me"
    href = "about"
    icon = "fa-user"

[[params.contents]]
    name = "portfolio"
    title = "Portfolio"
    href = "portfolio"
    icon = "fa-th"

[[params.contents]]
    name = "contact"
    title = "Contact"
    href = "contact"
    icon = "fa-envelope"

# contents in portfolio
[[params.portfolio]]
    title = "Ipsum Feugiat"
    alt = ""
    source = "img/pic02.jpg"
    url = "#"

[[params.portfolio]]
    title = "Rhoncus Semper"
    alt = ""
    source = "img/pic03.jpg"
    url = "#"

[[params.portfolio]]
    title = "Magna Nullam"
    alt = ""
    source = "img/pic04.jpg"
    url = "#"

[[params.portfolio]]
    title = "Natoque Vitae"
    alt = ""
    source = "img/pic05.jpg"
    url = "#"

[[params.portfolio]]
    title = "Dolor Penatibus"
    alt = ""
    source = "img/pic06.jpg"
    url = "#"

[[params.portfolio]]
    title = "Orci Convallis"
    alt = ""
    source = "img/pic07.jpg"
    url = "#"


[social]
    twitter = "EisKern"
    github = "EisKern"
    facebook = ""
    dribbble = ""
    email = ""
