author = "YuK"
baseurl = "https://sample.com/"
copyright = "YuK"
disqusshortname = ""
googleanalytics = ""
title = "Prologue by YuK"
theme = "prologue"

languageCode = "en-us"

[params]
    name = "YuK (EisKern)"
    description = "Student"
    avatar = "https://twitter.com/EisKern/photo"
    favicon = ""

# intro(top), about, portfolio, contact
[[params.contents]]
    name = "intro"
    title = "Intro"
    href = "top"
    icon = "fa-home"
    banner = "banner"
    homepage_title = "Hi! I'm <strong>Prologue</strong>, a <a href=\"http://html5up.net/license\">free</a> responsive<br /> site template designed by <a href=\"http://html5up.net\">HTML5 UP</a>."
    description = "Ligula scelerisque justo sem accumsan diam quis<br /> vitae natoque dictum sollicitudin elementum."

[[params.contents]]
    name = "about"
    title = "About Me"
    href = "about"
    icon = "fa-user"
    img = "img/about.jpg"
    description = "Tincidunt eu elit diam magnis pretium accumsan etiam id urna. Ridiculus ultricies curae quis et rhoncus velit. Lobortis elementum aliquet nec vitae laoreet eget cubilia quam non etiam odio tincidunt montes. Elementum sem parturient nulla quam placerat viverra mauris non cum elit tempus ullamcorper dolor. Libero rutrum ut lacinia donec curae mus vel quisque sociis nec ornare iaculis."

[[params.contents]]
    name = "portfolio"
    title = "Portfolio"
    href = "portfolio"
    icon = "fa-th"
    description = "Vitae natoque dictum etiam semper magnis enim feugiat convallis convallis egestas rhoncus ridiculus in quis risus amet curabitur tempor orci penatibus. Tellus erat mauris ipsum fermentum etiam vivamus eget. Nunc nibh morbi quis fusce hendrerit lacus ridiculus."

[[params.contents]]
    name = "contact"
    title = "Contact"
    href = "contact"
    icon = "fa-envelope"
    description = "Elementum sem parturient nulla quam placerat viverra mauris non cum elit tempus ullamcorper dolor. Libero rutrum ut lacinia donec curae mus. Eleifend id porttitor ac ultricies lobortis sem nunc orci ridiculus faucibus a consectetur. Porttitor curae mauris urna mi dolor."


# contents in portfolio
[[params.portfolio]]
    title = "Qiita"
    alt = ""
    source = "img/qiita.png"
    url = "https://qiita.com/EisKern"

[[params.portfolio]]
    title = "Tech Blog"
    alt = ""
    source = "img/blog-top.png"
    url = "https://www.tech-ek.com"

[[params.portfolio]]
    title = "Tic Toc Toe"
    alt = ""
    source = "img/tic-toc-toe-top.png"
    url = "https://tic-tac-toe.eiskern.com/"

[[params.portfolio]]
    title = "Search Book Cover"
    alt = ""
    source = "img/search-book-cover-top.png"
    url = "https://transparent-book-cover-search.herokuapp.com/"

[[params.portfolio]]
    title = "Treasure Hunt in Terminal (Linux)"
    alt = ""
    source = "img/treasure-hunt.png"
    url = ""

[[params.portfolio]]
    title = "Standard App in JavaFX"
    alt = ""
    source = "img/standard-app.png"
    url = ""


[social]
    twitter = "EisKern"
    github = "EisKern"
    facebook = ""
    dribbble = ""
    email = ""
